#!/bin/bash

echo "===== System Info ====="

echo "User: $(whoami)"

echo "Hostname: $(hostname)"

echo "OS: $(uname -o)"

echo "Kernel: $(uname -r)"

echo "Uptime: $(uptime -p)"

echo "CPU: $(nproc) cores"

echo "RAM: $(free -h | awk '/^Mem:/ {print $2}')"

echo "Disk: $(df -h / | awk 'NR==2 {print $4}') free"

echo "======================"
